/**********************************/
/* Table Name: 글 좋아요 */
/**********************************/
DROP TABLE COMMUNITYLIKES CASCADE CONSTRAINTS;
DROP TABLE COMMUNITYLIKES;
CREATE TABLE COMMUNITYLIKES(
		COMMUNITYLIKESNO              		NUMBER(10)		 NOT NULL		 PRIMARY KEY,
		CNT                           		NUMBER(10)		 DEFAULT 0		 NOT NULL,
		COMMUNITYNO                   		NUMBER(10)		 NULL ,
		MEMBERNO                      		NUMBER(10)		 NULL ,
  FOREIGN KEY (COMMUNITYNO) REFERENCES COMMUNITY (COMMUNITYNO),
  FOREIGN KEY (MEMBERNO) REFERENCES MEMBER (MEMBERNO)
);

COMMENT ON TABLE COMMUNITYLIKES is '글 좋아요';
COMMENT ON COLUMN COMMUNITYLIKES.COMMUNITYLIKESNO is '글 좋아요 번호';
COMMENT ON COLUMN COMMUNITYLIKES.CNT is '글 좋아요 수';
COMMENT ON COLUMN COMMUNITYLIKES.COMMUNITYNO is '커뮤니티번호';
COMMENT ON COLUMN COMMUNITYLIKES.MEMBERNO is '회원번호';

DROP SEQUENCE communitylikes_seq;

CREATE SEQUENCE communitylikes_seq
  START WITH 1                -- 시작 번호
  INCREMENT BY 1            -- 증가값
  MAXVALUE 9999999999  -- 최대값: 9999999999 --> NUMBER(10) 대응
  CACHE 2                        -- 2번은 메모리에서만 계산
  NOCYCLE;                  -- 다시 1부터 생성되는 것을 방지 